topics:
- /camera_array/cam0/image_raw
- /camera_array/cam2/image_raw
- /camera_array/cam4/image_raw
#- /zed2i/zed_node/left_raw/image_raw_color
#- /zed2i/zed_node/right_raw/image_raw_color


frequency: 1
viz : True
start_time: 0 # in seconds
end_time:  5000  # in seconds
calib: False
board_rows: 16
board_cols: 9
invert: False
gray: True
save_type: jpg

